name: raahi_app
description: Minimal Raahi scaffold (blueprint)
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  http: ^0.13.0
  url_launcher: ^6.1.7
  firebase_core: ^2.12.0
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.2.0
  firebase_messaging: ^14.6.0
  geolocator: ^9.0.2
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
